// Data-module checks for core/data/*.json (generated by tools/gen-guide-data.py).
// Pure JSON assertions: no engine code is loaded here.
//
//   node tests/test-data.cjs                      # run the checks
//   DATA_TEST_NEGATIVE=1 node tests/test-data.cjs # negative control: one assertion is made wrong on purpose
const fs = require("fs");
const path = require("path");

const dataDir = path.join(__dirname, "..", "core", "data");
const negative = process.env.DATA_TEST_NEGATIVE === "1";
let failures = 0;
let checks = 0;

function canon(v) {
  if (Array.isArray(v)) return v.map(canon);
  if (v && typeof v === "object") return Object.fromEntries(Object.keys(v).sort().map((k) => [k, canon(v[k])]));
  return v;
}

function check(label, actual, expected) {
  checks++;
  const a = JSON.stringify(canon(actual));
  const e = JSON.stringify(canon(expected));
  if (a !== e) {
    failures++;
    console.error(`FAIL ${label}\n  expected ${e}\n  actual   ${a}`);
  }
}

function load(name) {
  const text = fs.readFileSync(path.join(dataDir, name), "utf8");
  const obj = JSON.parse(text); // throws on invalid JSON
  check(`${name} ends with a single newline`, text.endsWith("}\n") && !text.endsWith("\n\n"), true);
  return obj;
}

const s3 = load("species-gen3.json");
const s4 = load("species-gen4.json");
const e3 = load("encounters-gen3.json");
const e4 = load("encounters-gen4.json");
const st3 = load("statics-gen3.json");
const st4 = load("statics-gen4.json");

// (c) species counts
check("gen3 species count", s3.species.length, 386);
check("gen3 meta species_count", s3.meta.species_count, 386);
check("gen3 dex numbers are 1..386 in order", s3.species.map((s) => s.dex), Array.from({ length: 386 }, (_, i) => i + 1));
check("gen4 species count", s4.species.length, 493);
check("gen4 dex numbers are 1..493 in order", s4.species.map((s) => s.dex), Array.from({ length: 493 }, (_, i) => i + 1));
check("gen3 internal ids skip the old Unown slots", s3.species.filter((s) => s.internal_id >= 252 && s.internal_id <= 276).length, 0);
check("gen3 Treecko internal id", s3.species.find((s) => s.constant === "SPECIES_TREECKO").internal_id, 277);

// (b) gender ratio bytes, in all three Gen 3 games and all three Gen 4 games
function byConst(file, c) {
  const s = file.species.find((x) => x.constant === c);
  if (!s) throw new Error(`missing ${c}`);
  return s;
}
const genderCases = [
  ["SPECIES_SNORLAX", negative ? 30 : 31], // 12.5% female
  ["SPECIES_BULBASAUR", 31], // 87.5% male
  ["SPECIES_NIDORAN_F", 254], // always female
  ["SPECIES_NIDORAN_M", 0], // always male
  ["SPECIES_MAGNEMITE", 255], // genderless
  ["SPECIES_CHANSEY", 254],
  ["SPECIES_TAUROS", 0],
  ["SPECIES_PIKACHU", 127], // 50%
  ["SPECIES_CLEFAIRY", 191], // 75% female
  ["SPECIES_GROWLITHE", 63], // 25% female
];
for (const [c, byte] of genderCases) {
  const a = byConst(s3, c);
  check(`gen3 ${c} gender byte (Emerald)`, a.gender_ratio, byte);
  check(`gen3 ${c} gender byte agrees in Ruby and FireRed`, a.game_differences ? Object.values(a.game_differences).some((d) => d && "gender_ratio" in d) : false, false);
  const b = byConst(s4, c);
  check(`gen4 ${c} gender byte (Platinum)`, b.gender_ratio, byte);
  check(`gen4 ${c} gender byte agrees in HeartGold and Diamond`, b.game_differences ? Object.values(b.game_differences).some((d) => d && "gender_ratio" in d) : false, false);
}
check("gen3 Snorlax abilities", byConst(s3, "SPECIES_SNORLAX").abilities, ["IMMUNITY", "THICK_FAT"]);
check("gen4 Snorlax abilities", byConst(s4, "SPECIES_SNORLAX").abilities, ["IMMUNITY", "THICK_FAT"]);
check("gen4 has no hidden abilities", s4.species.every((s) => s.hidden_ability === null), true);
check("gen4 Nidoran-F gained Rivalry in Gen 4", byConst(s4, "SPECIES_NIDORAN_F").abilities, ["POISON_POINT", "RIVALRY"]);
check("gen3 Nidoran-F had one ability", byConst(s3, "SPECIES_NIDORAN_F").abilities, ["POISON_POINT", "NONE"]);
check("gen3->gen4 difference list mentions Nidoran-F abilities",
  s4.meta.differences_from_gen3.some((d) => d.constant === "SPECIES_NIDORAN_F" && d.field === "abilities"), true);
check("gen3 base stats Bulbasaur", byConst(s3, "SPECIES_BULBASAUR").base_stats, { hp: 45, atk: 49, def: 49, spe: 45, spa: 65, spd: 65 });
check("gen4 base stats Bulbasaur", byConst(s4, "SPECIES_BULBASAUR").base_stats, { hp: 45, atk: 49, def: 49, spe: 45, spa: 65, spd: 65 });
check("gen4 types Bulbasaur", byConst(s4, "SPECIES_BULBASAUR").types, ["GRASS", "POISON"]);
check("gen4 egg groups Bulbasaur", byConst(s4, "SPECIES_BULBASAUR").egg_groups, ["MONSTER", "GRASS"]);

// (a) slot-rate arrays and a few table facts
check("gen3 land slot rates", e3.meta.slot_rates.land, [20, 20, 10, 10, 10, 10, 5, 5, 4, 4, 1, 1]);
check("gen3 water slot rates", e3.meta.slot_rates.water, [60, 30, 5, 4, 1]);
check("gen3 fishing slot rates", e3.meta.slot_rates.fishing, { old_rod: [70, 30], good_rod: [60, 20, 20], super_rod: [40, 40, 15, 4, 1] });
check("gen4 DPPt grass slot rates", e4.meta.slot_rates.dppt.grass, [20, 20, 10, 10, 10, 10, 5, 5, 4, 4, 1, 1]);
check("gen4 HGSS fishing slot rates", e4.meta.slot_rates.hgss.fishing_all_rods, [40, 30, 15, 10, 5]);
check("gen3 games present", Object.keys(e3.games).sort(), ["emerald", "firered", "leafgreen", "ruby", "sapphire"]);
check("gen4 games present", Object.keys(e4.games).sort(), ["diamond", "heartgold", "pearl", "platinum", "soulsilver"]);
const r101 = e3.games.emerald.maps.find((m) => m.map === "MAP_ROUTE101");
check("Emerald Route 101 land rate", r101.land.rate, 20);
check("Emerald Route 101 land slots", r101.land.slots.map((s) => [s.species, s.min_level]),
  [[265, 2], [261, 2], [265, 2], [265, 3], [261, 3], [261, 3], [265, 3], [261, 3], [263, 2], [263, 2], [263, 3], [263, 3]]);
check("Emerald Route 101 has 12 land slots", r101.land.slots.length, 12);
check("Emerald map count", e3.games.emerald.maps.length, 124);
const r201 = e4.games.platinum.tables.find((t) => t.table === "encounters_route_201");
check("Platinum Route 201 grass rate", r201.grass.rate, 30);
check("Platinum Route 201 grass slots", r201.grass.slots.map((s) => [s.species, s.level]),
  [[396, 2], [399, 2], [396, 3], [401, 3], [396, 3], [399, 3], [396, 3], [399, 3], [396, 2], [399, 2], [396, 2], [399, 2]]);
check("Platinum Route 201 maps", r201.maps, ["MAP_HEADER_ROUTE_201"]);
check("Platinum table count", e4.games.platinum.tables.length, 183);
check("HGSS table count", e4.games.heartgold.tables.length, 142);
check("D/P table count", e4.games.diamond.tables.length, 183);
const r29 = e4.games.heartgold.tables.find((t) => t.table === "R29");
check("HeartGold Route 29 morning slot 0", [r29.land.slots[0].morning.species, r29.land.slots[0].level], [16, 2]);
check("HeartGold Route 29 night slot 0 is Hoothoot", r29.land.slots[0].night.species, 163);
const r29ss = e4.games.soulsilver.tables.find((t) => t.table === "R29");
check("Route 29 slot 7 differs by version (HG Sentret L2 / SS Rattata L4)",
  [r29.land.slots[7].morning.species, r29.land.slots[7].level, r29ss.land.slots[7].morning.species, r29ss.land.slots[7].level], [161, 2, 19, 4]);
const monean = e3.games.firered.maps.find((m) => m.map === "MAP_SEVEN_ISLAND_TANOBY_RUINS_MONEAN_CHAMBER");
check("FRLG Monean chamber Unown letters", monean.land.unown_letters.join(""), "AAAAAAAAAAA?");

// statics
function stat(file, id) {
  const s = file.entries.find((x) => x.id === id);
  if (!s) throw new Error(`missing static ${id}`);
  return s;
}
check("Rayquaza RSE level", stat(st3, "rse/legend/rayquaza").level, 70);
check("Rayquaza RSE games", stat(st3, "rse/legend/rayquaza").games, ["ruby", "sapphire", "emerald"]);
check("Mewtwo FRLG level", stat(st3, "frlg/legend/mewtwo").level, 70);
check("Ruby Groudon Cave of Origin level", stat(st3, "ruby/legend/groudon").level, 45);
check("Emerald Kyogre Marine Cave level", stat(st3, "e/legend/kyogre").level, 70);
check("FRLG roamers level", stat(st3, "frlg/roamer/suicune").level, 50);
check("Giratina Platinum level", stat(st4, "pt/legend/giratina").level, 47);
check("Regigigas Platinum level", stat(st4, "pt/legend/regigigas").level, 1);
check("HeartGold Lugia level", stat(st4, "hg/legend/lugia").level, 70);
check("SoulSilver Lugia level", stat(st4, "ss/legend/lugia").level, 45);
check("HGSS red Gyarados is forced shiny", stat(st4, "hgss/static/gyarados").shiny, "always");
check("HGSS roamer Raikou level", stat(st4, "hgss/roamer/raikou").level, 40);
check("Diamond/Pearl entries are marked PokeFinder-provenance", st4.entries.filter((e) => e.id.startsWith("dp/") || e.id.startsWith("d/") || e.id.startsWith("p/")).every((e) => e.provenance === "pokefinder" && e.level_verified_against_decomp === false), true);
check("every decomp-provenance static cites at least one source line", st3.entries.concat(st4.entries).filter((e) => e.provenance === "decomp").every((e) => e.sources.length > 0 && e.sources.every((s) => typeof s.line === "number" && s.text.length > 0)), true);
check("static ids are unique (gen3)", new Set(st3.entries.map((e) => e.id)).size, st3.entries.length);
check("static ids are unique (gen4)", new Set(st4.entries.map((e) => e.id)).size, st4.entries.length);

if (failures) {
  console.error(`${failures} of ${checks} data checks failed${negative ? " (negative control: expected)" : ""}`);
  process.exit(1);
}
console.log(`data checks OK (${checks} assertions)`);
